---
title: ""
---

<br><br>

The following is a list of online resources that you might find useful:     

<br>

**Online references**

- [The tidyverse](http://tidyverse.org)
- [Quick-R](http://www.statmethods.net/)
- [Cookbook for R](http://www.cookbook-r.com/)
- [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)


**Books**

- [R 4 Data Science](https://r4ds.had.co.nz/)
- [Introduction to Statistical Learning in R](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Seventh%20Printing.pdf)
- [Andy Fields Discovering Statistics using R](https://uk.sagepub.com/en-gb/eur/discovering-statistics-using-r/book236067)
- [Bookdown book](https://bookdown.org/yihui/bookdown/)
- [Tidy text](https://www.tidytextmining.com/)
- [Geocomputation with R](https://geocompr.robinlovelace.net/)


**Style guides**

- [The tidyverse style guide](http://style.tidyverse.org/)
- [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml)

**Videos**

- [Google Developers: Intro to R](https://www.youtube.com/playlist?list=PLOU2XLYxmsIK9qQfztXeybpHvru-TrqAP)
- [RStudio webinars](https://www.rstudio.com/resources/webinars/)
- [Johns Hopkins Data Science Specialization](https://www.coursera.org/specializations/jhu-data-science) on Coursera
- [UserR! 2017 Session Videos](https://channel9.msdn.com/Events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference)

**Blogs**

- [R-bloggers](https://www.r-bloggers.com/)
- [R Weekly](https://rweekly.org/)
- [FlowingData](http://flowingdata.com/)
- [Machlis Musings](http://www.computerworld.com/author/Sharon-Machlis/)

**Communities**

- [StackOverflow](https://stackoverflow.com/questions/tagged/r)
- [RStudio Community](https://community.rstudio.com)
- [Twitter #rstats hashtag](https://twitter.com/search?q=%23rstats&src=tyah)

**R user groups**

- [Manchester R](http://www.rmanchester.org/)
- [London R](http://www.londonr.org/)
- [R-Ladies](https://rladies.org)

**Data visualisation**

- [Edward Tufte](https://www.edwardtufte.com/tufte/)
- [The Functional Art](http://www.thefunctionalart.com)
- [Storytelling with Data](http://www.storytellingwithdata.com)
- [Chartable by Datawrapper](https://blog.datawrapper.de)

**Data sources**

- [Gapminder](http://www.gapminder.org/data/)
- [Our World in Data](https://ourworldindata.org)
- [FiveThirtyEight](https://github.com/fivethirtyeight/data)
- [ProPublica](https://www.propublica.org/datastore/)

<br>
<br>